### ISSUE TITLE
Unknown type name ‘stack_t’

### ISSUE THREAD

**Issue by ImmortalTurtle** [AntonKozlov/eduos#26] opened 2017-10-23 11:34 UTC
The last commit broke eduos: in the process of building it prints "error: unknown type name ‘stack_t’".
[Report from travis](https://travis-ci.org/AntonKozlov/eduos/jobs/289700143#L457)

This problem is *supposed* to be solved by defining _GNU_SOURCE in Makefile, but we have already done that. Not clear what is the source of the problem.

**Comment by AntonKozlov** [comment] 2017-10-24 21:10
Thanks for noting! My bad, haven't carefully checked travis output
Your fix is valid as it should fix the fail. 
But the root cause is sched.h that was exported to application as kernel interface. It should not be done, so I suppose to rewrite mutex test to use proper kernel interace (syscalls). Could you please review the

**Comment by ImmortalTurtle** [comment] 2017-10-24 21:57
Oh, I see know what was causing the problem.That's true, we shouldn't have access to any kernel's insides (i.e. "os/sched.h") in apps. 
Sure, I like this solution much better as it fixes the root of the problem.

**Comment by AntonKozlov** [comment] 2017-10-24 22:31
The fix is merged into master, travis reports `eduos_shell` is passing. Thanks!

**Closed by AntonKozlov** 2017-10-24 22:31 UTC
